### ISSUE TITLE
chef-simple proposal (support for yaml like ansible)

### ISSUE THREAD

**Issue by gankkank** [opscode/chef#2776]
I didn't read chef-apply source code. I just explain my idea here (for newbies ?):

How to run: `./chef-simple.rb nginx.yml | sudo chef-apply -s`

* nginx.yml

```yml
#apt_repository:
#  ruby-ng:
#    uri: "ppa:brightbox/ruby-ng"

package:
#  nginx:
#  ruby2.2:
  nginx-full:
#  php5-fpm:

directory:
  "/opt/site/1":
    recursive: true
  "/opt/site/2":
  
service: 
  nginx:
    supports: ":status => true, :restart => true, :reload => true"
#    provider: Chef::Provider::Service::Upstart
    action:
     - :enable
     - :start
    
file:
  "/tmp/motd":
    owner: '"root"'
    group: '"root"'
    mode: '"0755"'
    content: '"this is a sample file"'
```

* chef-simple.rb

```ruby
#!/usr/bin/env ruby

require "psych"

recipe_path = ARGV[0]
funcs = Psych.load(File.read(recipe_path))

#puts funcs

funcs.each do |func, params|
  params.each do |param,opts|
    if opts
    #p opts
    options = opts.map { |k,v| "#{k} #{v}" }.join("\n  ")
    puts <<-EOH.gsub(/^ {6}/,'')
      #{func} "#{param}" do
        #{options}
      end
      EOH
    else
    puts <<-EOH.gsub(/^ {6}/,'')
      #{func} "#{param}"
      EOH
    end
  end
end
# `chef-apply -s #{STDIN}`
```

**Comment by lamont-granquist** [comment]
Well, first thing is that it's better for this development to happen in a cookbook outside of chef-client core.

The second thing is that this would be covered as an aspect of the dialects proposal: opscode/chef-rfc#71, and accepting anything like this into core chef would be its own RFC.

The third thing is that this being "for newbies" hugely violates the Law of Primacy:  http://en.wikipedia.org/wiki/Principles_of_learning#Primacy.  You're going to teach "newbies" one "simple" way of doing things and then switch everything once they've gotten far enough which is terrible for learning.

And Ansible's format of moustache-templated YAML files is a terrible approach for people who are terrified of programming languages, IMO its not something that should be emulated.

And I still don't understand how writing this:

```
file:
  "/tmp/motd":
    owner: '"root"'
    group: '"root"'
    mode: '"0755"'
    content: '"this is a sample file"'
```

Is any simpler than this:

```
fie "/tmp/motd" do
  owner "root"
  group "root"
  mode "0755" 
  content "this is a sample file"
end
```

I still can't look at those two examples and think anything other than the fact that you've actually got more to explain with the semantic meaning of the indentation in the YAML file, and the need to protect "/tmp/motd" with quotes while "owner" doesn't get the same treatment, etc.
